# **Model1 : RandomForest/ Lgbm/ GradientBoosting Ensemble**

## 1. Libraries

In [72]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from string import ascii_lowercase
from itertools import combinations

import lightgbm as lgb
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import  GradientBoostingClassifier

from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

## 2. Loading the data

In [73]:
train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test_x.csv')

## 4. Feature Engineering

In [74]:
x_train = train.copy()
x_train.drop('voted', axis=1, inplace = True)
y_train = train['voted']

In [75]:
dataset = [x_train, test]

### 마키아밸리 테스트 FE

In [76]:
questions = [i for i in list(ascii_lowercase)[:20]]
answers = [('Q'+i+'A') for i in questions]

In [77]:
for data in dataset:
  data['T'] = data['QcA'] - data['QfA'] + data['QoA'] - data['QrA'] + data['QsA']
  data['V'] = data['QbA'] - data['QeA'] + data['QhA'] + data['QjA'] + data['QmA'] - data['QqA']
  # data['M'] = - data['QkA']

Tactic/ Morality/ View에 따라 feature 항목을 나눠보았습니다.

In [78]:
flipping_columns = ["QeA", "QfA", "QkA", "QqA", "QrA"]
for data in dataset:
  for flip in flipping_columns: 
    data[flip] = 6 - data[flip]

In [79]:
flipping_secret_columns = ["QaA", "QdA", "QgA", "QiA", "QnA"]
for data in dataset:
  for flip in flipping_secret_columns: 
    data[flip] = 6 - data[flip]

In [80]:
for data in dataset:
  data['Mach_score'] = data[answers].mean(axis = 1)

In [81]:
for data in dataset:
  data['delay'] = data[[('Q'+i+'E') for i in questions]].sum(axis=1)
  data['delay'] = data['delay'] ** (1/10)

In [82]:
Ancoms = list(combinations(answers, 2))
for data in dataset:
  for a,b in Ancoms:
    data['%s_dv_%s'%(a,b)] = data[a]/data[b]

In [83]:
for data in dataset:
  data.drop([('Q'+i+'A') for i in questions], axis = 1, inplace = True)
  data.drop([('Q'+i+'E') for i in questions], axis = 1, inplace = True)

### 나머지 Features

In [84]:
for data in dataset:
  data.drop('hand', axis=1, inplace = True)

In [85]:
wr_list = [('wr_0'+str(i)) for i in range(1,10)]
wr_list.extend([('wr_'+str(i)) for i in range(10,14)])
wr_no_need = [i for i in wr_list if i not in ['wr_01', 'wr_03', 'wr_06', 'wr_09', 'wr_11']]

EDA에서 결과에 큰 영향이 없다고 판단된 feature들을 제거해주었습니다.

In [86]:
for data in dataset:
  data.drop(wr_no_need, axis=1, inplace = True)

In [87]:
for data in dataset:
  data['Ex'] = (data['tp01']+data['tp06'])/2
  data['Ag'] = (data['tp07']+data['tp02'])/2
  data['Con'] = (data['tp03']+data['tp08'])/2
  data['Es'] =(data['tp09']+data['tp04'])/2
  data['Op'] =(data['tp05']+data['tp10'])/2

TIPI test에 따라 feature 항목을 나눠놓았는데, 이때는 tipi feature들이 flip된 형태로 저장되어있는지 몰라서 따로 전처리를 해주지 않았었습니다.

In [88]:
for data in dataset:
  data.drop([('tp0'+str(i)) for i in range(1,10)], axis=1, inplace = True)
  data.drop('tp10', axis = 1, inplace = True)

In [89]:
index = test['index']
for data in dataset:
  data.drop('index', axis = 1, inplace = True)

In [90]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
needenco = ['age_group', 'gender', 'race', 'religion']
for i in needenco:
  x_train[i] = encoder.fit_transform(x_train[i])
  test[i] = encoder.transform(test[i])

# SHAP

In [ ]:
# from catboost import CatBoostClassifier
# import shap
# import matplotlib.pyplot as plt
# plt.rc('font', family='Malgun Gothic')

# X = x_train.copy()
# y = list(map(lambda x: 0 if x==1 else 1, y_train))

# model = CatBoostClassifier(
#     # iterations=5, 
#     # learning_rate=0.1, 
#     # loss_function='CrossEntropy'
# )
# model.fit(X, y)

# # explain the model's predictions using SHAP
# # (same syntax works for LightGBM, CatBoost, scikit-learn, transformers, Spark, etc.)
# explainer = shap.TreeExplainer(model)
# shap_values = explainer(X)
# shap.initjs()

# # visualize the first prediction's explanation
# shap.plots.waterfall(shap_values[0])
# shap.summary_plot(shap_values, X, plot_type="bar")
# shap.plots.force(shap_values[0])

In [ ]:
# import numpy as np

# vals = np.abs(shap_values.values).mean(0)
# feature_names = X.columns

# feature_importance = pd.DataFrame(list(zip(feature_names, vals)),columns=['col_name','feature_importance_vals'])
# feature_importance.sort_values(by=['feature_importance_vals'],ascending=False, inplace=True)
# feature_importance.head()

In [ ]:
# shap.plots.bar(shap_values, max_display=300)

In [20]:
# shap.plots.beeswarm(shap_values, max_display=350)

In [ ]:
# feature_importance[feature_importance['col_name']=='QmA_dv_QpA']

In [ ]:
# temp_ls = []
# for i in feature_importance.index:
#     if i!=185:
#         temp_ls.append(feature_importance.loc[i]['col_name'])
#     else:
#         break

In [ ]:
# len(temp_ls)

## 5. Model

In [91]:
from pycaret.classification import *

x_train['target'] = list(map(lambda x: 0 if x==1 else 1,y_train))

In [92]:
setup_clf = setup(data=x_train, target='target')

In [93]:
best_3 = compare_models(sort = 'AUC', n_select = 3)

Processing:   0%|          | 0/67 [00:00<?, ?it/s]

In [94]:
blended = blend_models(estimator_list = best_3, fold = 5, method = 'soft')

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [95]:
pred_holdout = predict_model(blended)

In [96]:
final_model = finalize_model(blended)

In [97]:
predictions = predict_model(final_model, data = test)

In [98]:
predictions['Score']

0        0.7073
1        0.8880
2        0.5873
3        0.7865
4        0.7393
          ...
11378    0.5603
11379    0.8507
11380    0.7638
11381    0.6889
11382    0.5133
Name: Score, Length: 11383, dtype: float64

In [100]:
submission = pd.DataFrame({
    "index" : index,
    "voted" : predictions['Score']
})
submission.to_csv('./data/model1.csv', index=False)

In [21]:
k_fold = KFold(n_splits = 3, shuffle = True, random_state = 0)

In [24]:
from catboost import CatBoostClassifier

clf1 = RandomForestClassifier(n_estimators=500)
clf2 = LGBMClassifier()
clf3 = GradientBoostingClassifier()
clf4 = CatBoostClassifier()

soft_vote  = VotingClassifier([('r1',clf1), ('r2', clf2), ('r3',clf3), ('r4',clf4)], voting='soft')
soft_vote.fit(x_train, y_train)

Learning rate set to 0.052606
0:	learn: 0.6769188	total: 67.5ms	remaining: 1m 7s
1:	learn: 0.6658066	total: 85.8ms	remaining: 42.8s
2:	learn: 0.6559653	total: 100ms	remaining: 33.3s
3:	learn: 0.6474527	total: 114ms	remaining: 28.4s
4:	learn: 0.6365732	total: 128ms	remaining: 25.5s
5:	learn: 0.6277312	total: 143ms	remaining: 23.7s
6:	learn: 0.6201719	total: 156ms	remaining: 22.2s
7:	learn: 0.6153279	total: 169ms	remaining: 21s
8:	learn: 0.6108046	total: 183ms	remaining: 20.1s
9:	learn: 0.6075068	total: 195ms	remaining: 19.3s
10:	learn: 0.6046391	total: 208ms	remaining: 18.7s
11:	learn: 0.6013761	total: 221ms	remaining: 18.2s
12:	learn: 0.5988660	total: 231ms	remaining: 17.6s
13:	learn: 0.5957185	total: 243ms	remaining: 17.1s
14:	learn: 0.5919632	total: 256ms	remaining: 16.8s
15:	learn: 0.5889215	total: 267ms	remaining: 16.4s
16:	learn: 0.5873996	total: 277ms	remaining: 16s
17:	learn: 0.5853914	total: 289ms	remaining: 15.7s
18:	learn: 0.5837983	total: 299ms	remaining: 15.4s
19:	learn: 0.5813082	total: 310ms	remaining: 15.2s
20:	learn: 0.5803255	total: 321ms	remaining: 15s
21:	learn: 0.5792393	total: 332ms	remaining: 14.7s
22:	learn: 0.5774206	total: 342ms	remaining: 14.5s
23:	learn: 0.5763955	total: 353ms	remaining: 14.4s
24:	learn: 0.5755017	total: 364ms	remaining: 14.2s
25:	learn: 0.5740515	total: 374ms	remaining: 14s
26:	learn: 0.5732677	total: 385ms	remaining: 13.9s
27:	learn: 0.5724363	total: 396ms	remaining: 13.7s
28:	learn: 0.5718665	total: 406ms	remaining: 13.6s
29:	learn: 0.5710948	total: 417ms	remaining: 13.5s
30:	learn: 0.5705411	total: 428ms	remaining: 13.4s
31:	learn: 0.5700953	total: 438ms	remaining: 13.2s
32:	learn: 0.5695021	total: 448ms	remaining: 13.1s
33:	learn: 0.5687816	total: 459ms	remaining: 13s
34:	learn: 0.5684051	total: 468ms	remaining: 12.9s
35:	learn: 0.5681213	total: 479ms	remaining: 12.8s
36:	learn: 0.5677018	total: 489ms	remaining: 12.7s
37:	learn: 0.5670909	total: 499ms	remaining: 12.6s
38:	learn: 0.5666318	total: 509ms	remaining: 12.5s
39:	learn: 0.5663950	total: 520ms	remaining: 12.5s
40:	learn: 0.5659821	total: 531ms	remaining: 12.4s
41:	learn: 0.5656652	total: 541ms	remaining: 12.3s
42:	learn: 0.5652465	total: 552ms	remaining: 12.3s
43:	learn: 0.5648720	total: 562ms	remaining: 12.2s
44:	learn: 0.5646462	total: 571ms	remaining: 12.1s
45:	learn: 0.5644768	total: 581ms	remaining: 12s
46:	learn: 0.5642652	total: 590ms	remaining: 12s
47:	learn: 0.5636978	total: 601ms	remaining: 11.9s
48:	learn: 0.5634845	total: 610ms	remaining: 11.8s
49:	learn: 0.5631898	total: 619ms	remaining: 11.8s
50:	learn: 0.5627921	total: 630ms	remaining: 11.7s
51:	learn: 0.5624154	total: 641ms	remaining: 11.7s
52:	learn: 0.5621253	total: 651ms	remaining: 11.6s
53:	learn: 0.5619032	total: 662ms	remaining: 11.6s
54:	learn: 0.5616261	total: 673ms	remaining: 11.6s
55:	learn: 0.5614266	total: 682ms	remaining: 11.5s
56:	learn: 0.5611802	total: 693ms	remaining: 11.5s
57:	learn: 0.5610026	total: 703ms	remaining: 11.4s
58:	learn: 0.5608127	total: 713ms	remaining: 11.4s
59:	learn: 0.5606546	total: 724ms	remaining: 11.3s
60:	learn: 0.5604152	total: 733ms	remaining: 11.3s
61:	learn: 0.5602384	total: 742ms	remaining: 11.2s
62:	learn: 0.5600682	total: 753ms	remaining: 11.2s
63:	learn: 0.5597701	total: 762ms	remaining: 11.1s
64:	learn: 0.5596279	total: 772ms	remaining: 11.1s
65:	learn: 0.5594773	total: 782ms	remaining: 11.1s
66:	learn: 0.5593222	total: 792ms	remaining: 11s
67:	learn: 0.5591535	total: 803ms	remaining: 11s
68:	learn: 0.5590241	total: 813ms	remaining: 11s
69:	learn: 0.5585900	total: 823ms	remaining: 10.9s
70:	learn: 0.5584606	total: 833ms	remaining: 10.9s
71:	learn: 0.5582524	total: 843ms	remaining: 10.9s
72:	learn: 0.5580854	total: 854ms	remaining: 10.8s
73:	learn: 0.5579605	total: 863ms	remaining: 10.8s
74:	learn: 0.5577969	total: 873ms	remaining: 10.8s
75:	learn: 0.5574373	total: 883ms	remaining: 10.7s
76:	learn: 0.5571419	total: 894ms	remaining: 10.7s
77:	learn: 0.5569961	total: 903ms	remaining: 10.7s
78:	learn: 0.5568991	total: 913ms	remaining: 10.6s
79:	learn: 0.5567746	total: 923ms	remaining: 10.6s
80:	learn: 0.5565732	total: 933ms	remaining: 10.6s
81:	learn: 0.5563924	total: 943ms	remaining: 10.6s
82:	learn: 0.5561367	total: 953ms	remaining: 10.5s
83:	learn: 0.5560479	total: 963ms	remaining: 10.5s
84:	learn: 0.5559299	total: 973ms	remaining: 10.5s
85:	learn: 0.5557757	total: 984ms	remaining: 10.5s
86:	learn: 0.5555096	total: 994ms	remaining: 10.4s
87:	learn: 0.5553581	total: 1s	remaining: 10.4s
88:	learn: 0.5551899	total: 1.01s	remaining: 10.4s
89:	learn: 0.5550586	total: 1.02s	remaining: 10.4s
90:	learn: 0.5549179	total: 1.03s	remaining: 10.3s
91:	learn: 0.5548082	total: 1.04s	remaining: 10.3s
92:	learn: 0.5547184	total: 1.06s	remaining: 10.3s
93:	learn: 0.5545809	total: 1.06s	remaining: 10.3s
94:	learn: 0.5544656	total: 1.07s	remaining: 10.2s
95:	learn: 0.5543308	total: 1.08s	remaining: 10.2s
96:	learn: 0.5541313	total: 1.09s	remaining: 10.2s
97:	learn: 0.5540082	total: 1.11s	remaining: 10.2s
98:	learn: 0.5539255	total: 1.12s	remaining: 10.2s
99:	learn: 0.5538390	total: 1.13s	remaining: 10.1s
100:	learn: 0.5536839	total: 1.14s	remaining: 10.1s
101:	learn: 0.5535669	total: 1.15s	remaining: 10.1s
102:	learn: 0.5532521	total: 1.16s	remaining: 10.1s
103:	learn: 0.5531477	total: 1.17s	remaining: 10.1s
104:	learn: 0.5530308	total: 1.18s	remaining: 10.1s
105:	learn: 0.5529178	total: 1.19s	remaining: 10s
106:	learn: 0.5528009	total: 1.2s	remaining: 10s
107:	learn: 0.5526939	total: 1.21s	remaining: 10s
108:	learn: 0.5525833	total: 1.22s	remaining: 9.99s
109:	learn: 0.5524728	total: 1.23s	remaining: 9.97s
110:	learn: 0.5523609	total: 1.24s	remaining: 9.95s
111:	learn: 0.5522554	total: 1.25s	remaining: 9.93s
112:	learn: 0.5520684	total: 1.26s	remaining: 9.91s
113:	learn: 0.5519105	total: 1.27s	remaining: 9.89s
114:	learn: 0.5518316	total: 1.28s	remaining: 9.88s
115:	learn: 0.5517166	total: 1.29s	remaining: 9.85s
116:	learn: 0.5516115	total: 1.3s	remaining: 9.83s
117:	learn: 0.5515041	total: 1.31s	remaining: 9.81s
118:	learn: 0.5514049	total: 1.32s	remaining: 9.79s
119:	learn: 0.5512982	total: 1.33s	remaining: 9.78s
120:	learn: 0.5511794	total: 1.34s	remaining: 9.76s
121:	learn: 0.5510820	total: 1.35s	remaining: 9.74s
122:	learn: 0.5508042	total: 1.36s	remaining: 9.73s
123:	learn: 0.5507071	total: 1.37s	remaining: 9.71s
124:	learn: 0.5505468	total: 1.39s	remaining: 9.7s
125:	learn: 0.5503532	total: 1.4s	remaining: 9.68s
126:	learn: 0.5502658	total: 1.41s	remaining: 9.67s
127:	learn: 0.5501707	total: 1.42s	remaining: 9.66s
128:	learn: 0.5500587	total: 1.43s	remaining: 9.64s
129:	learn: 0.5499815	total: 1.44s	remaining: 9.62s
130:	learn: 0.5498672	total: 1.45s	remaining: 9.61s
131:	learn: 0.5496923	total: 1.46s	remaining: 9.59s
132:	learn: 0.5495842	total: 1.47s	remaining: 9.58s
133:	learn: 0.5494804	total: 1.48s	remaining: 9.56s
134:	learn: 0.5493746	total: 1.49s	remaining: 9.55s
135:	learn: 0.5492262	total: 1.5s	remaining: 9.54s
136:	learn: 0.5491465	total: 1.51s	remaining: 9.53s
137:	learn: 0.5490319	total: 1.52s	remaining: 9.52s
138:	learn: 0.5489219	total: 1.53s	remaining: 9.5s
139:	learn: 0.5487941	total: 1.54s	remaining: 9.48s
140:	learn: 0.5486995	total: 1.55s	remaining: 9.47s
141:	learn: 0.5485906	total: 1.56s	remaining: 9.46s
142:	learn: 0.5484856	total: 1.57s	remaining: 9.44s
143:	learn: 0.5483504	total: 1.58s	remaining: 9.43s
144:	learn: 0.5482577	total: 1.6s	remaining: 9.41s
145:	learn: 0.5481515	total: 1.6s	remaining: 9.39s
146:	learn: 0.5480595	total: 1.62s	remaining: 9.38s
147:	learn: 0.5479721	total: 1.63s	remaining: 9.36s
148:	learn: 0.5479169	total: 1.64s	remaining: 9.35s
149:	learn: 0.5478421	total: 1.65s	remaining: 9.34s
150:	learn: 0.5477370	total: 1.66s	remaining: 9.33s
151:	learn: 0.5476408	total: 1.67s	remaining: 9.32s
152:	learn: 0.5474708	total: 1.68s	remaining: 9.3s
153:	learn: 0.5473623	total: 1.69s	remaining: 9.29s
154:	learn: 0.5472796	total: 1.7s	remaining: 9.28s
155:	learn: 0.5471927	total: 1.71s	remaining: 9.26s
156:	learn: 0.5470760	total: 1.72s	remaining: 9.24s
157:	learn: 0.5469848	total: 1.73s	remaining: 9.23s
158:	learn: 0.5468969	total: 1.74s	remaining: 9.22s
159:	learn: 0.5467796	total: 1.75s	remaining: 9.2s
160:	learn: 0.5466941	total: 1.76s	remaining: 9.18s
161:	learn: 0.5465735	total: 1.77s	remaining: 9.16s
162:	learn: 0.5464985	total: 1.78s	remaining: 9.15s
163:	learn: 0.5462720	total: 1.79s	remaining: 9.13s
164:	learn: 0.5460915	total: 1.8s	remaining: 9.12s
165:	learn: 0.5459927	total: 1.81s	remaining: 9.11s
166:	learn: 0.5459098	total: 1.82s	remaining: 9.09s
167:	learn: 0.5457875	total: 1.83s	remaining: 9.07s
168:	learn: 0.5456839	total: 1.84s	remaining: 9.06s
169:	learn: 0.5455626	total: 1.85s	remaining: 9.05s
170:	learn: 0.5454655	total: 1.86s	remaining: 9.03s
171:	learn: 0.5453583	total: 1.87s	remaining: 9.01s
172:	learn: 0.5452249	total: 1.88s	remaining: 9s
173:	learn: 0.5451165	total: 1.89s	remaining: 8.99s
174:	learn: 0.5450155	total: 1.9s	remaining: 8.97s
175:	learn: 0.5449111	total: 1.91s	remaining: 8.95s
176:	learn: 0.5448361	total: 1.92s	remaining: 8.94s
177:	learn: 0.5447268	total: 1.93s	remaining: 8.93s
178:	learn: 0.5446234	total: 1.94s	remaining: 8.92s
179:	learn: 0.5445319	total: 1.95s	remaining: 8.9s
180:	learn: 0.5444333	total: 1.96s	remaining: 8.89s
181:	learn: 0.5443539	total: 1.97s	remaining: 8.87s
182:	learn: 0.5441954	total: 1.99s	remaining: 8.86s
183:	learn: 0.5440626	total: 1.99s	remaining: 8.85s
184:	learn: 0.5439608	total: 2s	remaining: 8.83s
185:	learn: 0.5438466	total: 2.02s	remaining: 8.82s
186:	learn: 0.5437467	total: 2.02s	remaining: 8.81s
187:	learn: 0.5436200	total: 2.04s	remaining: 8.79s
188:	learn: 0.5435003	total: 2.05s	remaining: 8.78s
189:	learn: 0.5433759	total: 2.06s	remaining: 8.77s
190:	learn: 0.5432621	total: 2.07s	remaining: 8.76s
191:	learn: 0.5431185	total: 2.08s	remaining: 8.74s
192:	learn: 0.5430230	total: 2.09s	remaining: 8.73s
193:	learn: 0.5429154	total: 2.1s	remaining: 8.72s
194:	learn: 0.5427996	total: 2.11s	remaining: 8.71s
195:	learn: 0.5426886	total: 2.12s	remaining: 8.69s
196:	learn: 0.5425741	total: 2.13s	remaining: 8.67s
197:	learn: 0.5424723	total: 2.14s	remaining: 8.66s
198:	learn: 0.5423538	total: 2.15s	remaining: 8.65s
199:	learn: 0.5422617	total: 2.16s	remaining: 8.64s
200:	learn: 0.5421434	total: 2.17s	remaining: 8.63s
201:	learn: 0.5420229	total: 2.18s	remaining: 8.62s
202:	learn: 0.5419341	total: 2.19s	remaining: 8.6s
203:	learn: 0.5417872	total: 2.2s	remaining: 8.59s
204:	learn: 0.5416734	total: 2.21s	remaining: 8.58s
205:	learn: 0.5415416	total: 2.22s	remaining: 8.56s
206:	learn: 0.5414013	total: 2.23s	remaining: 8.55s
207:	learn: 0.5412806	total: 2.24s	remaining: 8.54s
208:	learn: 0.5411505	total: 2.25s	remaining: 8.53s
209:	learn: 0.5410130	total: 2.26s	remaining: 8.51s
210:	learn: 0.5408739	total: 2.27s	remaining: 8.5s
211:	learn: 0.5407517	total: 2.29s	remaining: 8.49s
212:	learn: 0.5406253	total: 2.29s	remaining: 8.48s
213:	learn: 0.5404873	total: 2.31s	remaining: 8.47s
214:	learn: 0.5403755	total: 2.31s	remaining: 8.45s
215:	learn: 0.5402407	total: 2.33s	remaining: 8.44s
216:	learn: 0.5400779	total: 2.34s	remaining: 8.43s
217:	learn: 0.5399453	total: 2.35s	remaining: 8.42s
218:	learn: 0.5398232	total: 2.36s	remaining: 8.41s
219:	learn: 0.5397041	total: 2.37s	remaining: 8.39s
220:	learn: 0.5395626	total: 2.38s	remaining: 8.38s
221:	learn: 0.5394246	total: 2.39s	remaining: 8.37s
222:	learn: 0.5392976	total: 2.4s	remaining: 8.36s
223:	learn: 0.5390878	total: 2.41s	remaining: 8.35s
224:	learn: 0.5388801	total: 2.42s	remaining: 8.33s
225:	learn: 0.5386967	total: 2.43s	remaining: 8.32s
226:	learn: 0.5385560	total: 2.44s	remaining: 8.31s
227:	learn: 0.5384357	total: 2.45s	remaining: 8.29s
228:	learn: 0.5383321	total: 2.46s	remaining: 8.28s
229:	learn: 0.5380924	total: 2.47s	remaining: 8.27s
230:	learn: 0.5379442	total: 2.48s	remaining: 8.26s
231:	learn: 0.5378210	total: 2.49s	remaining: 8.24s
232:	learn: 0.5376139	total: 2.5s	remaining: 8.22s
233:	learn: 0.5375042	total: 2.51s	remaining: 8.21s
234:	learn: 0.5373620	total: 2.52s	remaining: 8.2s
235:	learn: 0.5371106	total: 2.53s	remaining: 8.18s
236:	learn: 0.5369771	total: 2.54s	remaining: 8.17s
237:	learn: 0.5368607	total: 2.55s	remaining: 8.16s
238:	learn: 0.5367502	total: 2.56s	remaining: 8.15s
239:	learn: 0.5366128	total: 2.57s	remaining: 8.13s
240:	learn: 0.5364400	total: 2.58s	remaining: 8.12s
241:	learn: 0.5362660	total: 2.59s	remaining: 8.11s
242:	learn: 0.5361029	total: 2.6s	remaining: 8.09s
243:	learn: 0.5359503	total: 2.61s	remaining: 8.08s
244:	learn: 0.5357881	total: 2.62s	remaining: 8.06s
245:	learn: 0.5356350	total: 2.63s	remaining: 8.05s
246:	learn: 0.5354740	total: 2.64s	remaining: 8.04s
247:	learn: 0.5353291	total: 2.65s	remaining: 8.03s
248:	learn: 0.5351056	total: 2.66s	remaining: 8.02s
249:	learn: 0.5349451	total: 2.67s	remaining: 8s
250:	learn: 0.5348105	total: 2.68s	remaining: 7.99s
251:	learn: 0.5346606	total: 2.69s	remaining: 7.98s
252:	learn: 0.5344967	total: 2.7s	remaining: 7.97s
253:	learn: 0.5343666	total: 2.71s	remaining: 7.96s
254:	learn: 0.5342066	total: 2.72s	remaining: 7.94s
255:	learn: 0.5340646	total: 2.73s	remaining: 7.93s
256:	learn: 0.5339508	total: 2.74s	remaining: 7.92s
257:	learn: 0.5337902	total: 2.75s	remaining: 7.91s
258:	learn: 0.5336439	total: 2.76s	remaining: 7.9s
259:	learn: 0.5335322	total: 2.77s	remaining: 7.88s
260:	learn: 0.5333846	total: 2.78s	remaining: 7.87s
261:	learn: 0.5332361	total: 2.79s	remaining: 7.86s
262:	learn: 0.5331210	total: 2.8s	remaining: 7.85s
263:	learn: 0.5330274	total: 2.81s	remaining: 7.83s
264:	learn: 0.5328917	total: 2.82s	remaining: 7.82s
265:	learn: 0.5327366	total: 2.83s	remaining: 7.8s
266:	learn: 0.5326110	total: 2.84s	remaining: 7.79s
267:	learn: 0.5324359	total: 2.85s	remaining: 7.78s
268:	learn: 0.5322722	total: 2.86s	remaining: 7.76s
269:	learn: 0.5321280	total: 2.87s	remaining: 7.76s
270:	learn: 0.5320279	total: 2.88s	remaining: 7.74s
271:	learn: 0.5319195	total: 2.89s	remaining: 7.73s
272:	learn: 0.5317721	total: 2.9s	remaining: 7.72s
273:	learn: 0.5316138	total: 2.91s	remaining: 7.71s
274:	learn: 0.5314606	total: 2.92s	remaining: 7.7s
275:	learn: 0.5312637	total: 2.93s	remaining: 7.69s
276:	learn: 0.5311442	total: 2.94s	remaining: 7.67s
277:	learn: 0.5309986	total: 2.95s	remaining: 7.66s
278:	learn: 0.5308630	total: 2.96s	remaining: 7.65s
279:	learn: 0.5306623	total: 2.97s	remaining: 7.64s
280:	learn: 0.5305159	total: 2.98s	remaining: 7.63s
281:	learn: 0.5303806	total: 2.99s	remaining: 7.62s
282:	learn: 0.5302561	total: 3s	remaining: 7.61s
283:	learn: 0.5301009	total: 3.01s	remaining: 7.59s
284:	learn: 0.5299588	total: 3.02s	remaining: 7.58s
285:	learn: 0.5297896	total: 3.03s	remaining: 7.57s
286:	learn: 0.5296235	total: 3.04s	remaining: 7.56s
287:	learn: 0.5294771	total: 3.06s	remaining: 7.55s
288:	learn: 0.5293300	total: 3.06s	remaining: 7.54s
289:	learn: 0.5291865	total: 3.08s	remaining: 7.53s
290:	learn: 0.5290573	total: 3.08s	remaining: 7.52s
291:	learn: 0.5289261	total: 3.1s	remaining: 7.5s
292:	learn: 0.5287388	total: 3.1s	remaining: 7.49s
293:	learn: 0.5285947	total: 3.12s	remaining: 7.48s
294:	learn: 0.5284634	total: 3.13s	remaining: 7.47s
295:	learn: 0.5283586	total: 3.14s	remaining: 7.46s
296:	learn: 0.5282022	total: 3.15s	remaining: 7.45s
297:	learn: 0.5280743	total: 3.16s	remaining: 7.44s
298:	learn: 0.5278945	total: 3.17s	remaining: 7.42s
299:	learn: 0.5277636	total: 3.18s	remaining: 7.41s
300:	learn: 0.5276417	total: 3.19s	remaining: 7.4s
301:	learn: 0.5274963	total: 3.2s	remaining: 7.39s
302:	learn: 0.5273759	total: 3.21s	remaining: 7.38s
303:	learn: 0.5272304	total: 3.22s	remaining: 7.37s
304:	learn: 0.5270716	total: 3.23s	remaining: 7.36s
305:	learn: 0.5269419	total: 3.24s	remaining: 7.34s
306:	learn: 0.5268041	total: 3.25s	remaining: 7.33s
307:	learn: 0.5266507	total: 3.26s	remaining: 7.32s
308:	learn: 0.5265155	total: 3.27s	remaining: 7.31s
309:	learn: 0.5263541	total: 3.28s	remaining: 7.3s
310:	learn: 0.5262103	total: 3.29s	remaining: 7.28s
311:	learn: 0.5260640	total: 3.3s	remaining: 7.27s
312:	learn: 0.5259494	total: 3.31s	remaining: 7.27s
313:	learn: 0.5258191	total: 3.32s	remaining: 7.25s
314:	learn: 0.5257084	total: 3.33s	remaining: 7.24s
315:	learn: 0.5255879	total: 3.34s	remaining: 7.23s
316:	learn: 0.5254549	total: 3.35s	remaining: 7.22s
317:	learn: 0.5253002	total: 3.36s	remaining: 7.21s
318:	learn: 0.5251753	total: 3.37s	remaining: 7.2s
319:	learn: 0.5250258	total: 3.38s	remaining: 7.19s
320:	learn: 0.5249081	total: 3.39s	remaining: 7.18s
321:	learn: 0.5247491	total: 3.4s	remaining: 7.16s
322:	learn: 0.5246159	total: 3.41s	remaining: 7.15s
323:	learn: 0.5244512	total: 3.42s	remaining: 7.14s
324:	learn: 0.5243090	total: 3.43s	remaining: 7.13s
325:	learn: 0.5241959	total: 3.44s	remaining: 7.12s
326:	learn: 0.5240500	total: 3.45s	remaining: 7.11s
327:	learn: 0.5239449	total: 3.46s	remaining: 7.09s
328:	learn: 0.5238060	total: 3.47s	remaining: 7.08s
329:	learn: 0.5236741	total: 3.48s	remaining: 7.07s
330:	learn: 0.5235135	total: 3.49s	remaining: 7.06s
331:	learn: 0.5234035	total: 3.5s	remaining: 7.05s
332:	learn: 0.5232612	total: 3.51s	remaining: 7.04s
333:	learn: 0.5231100	total: 3.52s	remaining: 7.03s
334:	learn: 0.5229873	total: 3.53s	remaining: 7.02s
335:	learn: 0.5228467	total: 3.54s	remaining: 7.01s
336:	learn: 0.5227293	total: 3.56s	remaining: 7s
337:	learn: 0.5225851	total: 3.56s	remaining: 6.98s
338:	learn: 0.5224350	total: 3.58s	remaining: 6.97s
339:	learn: 0.5222684	total: 3.58s	remaining: 6.96s
340:	learn: 0.5221245	total: 3.6s	remaining: 6.95s
341:	learn: 0.5219772	total: 3.61s	remaining: 6.94s
342:	learn: 0.5218508	total: 3.62s	remaining: 6.93s
343:	learn: 0.5216769	total: 3.63s	remaining: 6.92s
344:	learn: 0.5215360	total: 3.64s	remaining: 6.91s
345:	learn: 0.5214109	total: 3.65s	remaining: 6.9s
346:	learn: 0.5212802	total: 3.66s	remaining: 6.89s
347:	learn: 0.5211459	total: 3.67s	remaining: 6.88s
348:	learn: 0.5210420	total: 3.68s	remaining: 6.86s
349:	learn: 0.5209165	total: 3.69s	remaining: 6.85s
350:	learn: 0.5207906	total: 3.7s	remaining: 6.84s
351:	learn: 0.5206418	total: 3.71s	remaining: 6.83s
352:	learn: 0.5204781	total: 3.72s	remaining: 6.82s
353:	learn: 0.5203477	total: 3.73s	remaining: 6.81s
354:	learn: 0.5202254	total: 3.74s	remaining: 6.79s
355:	learn: 0.5201157	total: 3.75s	remaining: 6.78s
356:	learn: 0.5199771	total: 3.76s	remaining: 6.77s
357:	learn: 0.5198575	total: 3.77s	remaining: 6.76s
358:	learn: 0.5196966	total: 3.78s	remaining: 6.75s
359:	learn: 0.5195651	total: 3.79s	remaining: 6.74s
360:	learn: 0.5194462	total: 3.8s	remaining: 6.73s
361:	learn: 0.5192957	total: 3.81s	remaining: 6.72s
362:	learn: 0.5191638	total: 3.82s	remaining: 6.71s
363:	learn: 0.5190193	total: 3.83s	remaining: 6.69s
364:	learn: 0.5189170	total: 3.84s	remaining: 6.68s
365:	learn: 0.5187620	total: 3.85s	remaining: 6.67s
366:	learn: 0.5186318	total: 3.86s	remaining: 6.66s
367:	learn: 0.5185008	total: 3.87s	remaining: 6.65s
368:	learn: 0.5183535	total: 3.88s	remaining: 6.64s
369:	learn: 0.5182224	total: 3.89s	remaining: 6.63s
370:	learn: 0.5181048	total: 3.9s	remaining: 6.62s
371:	learn: 0.5179866	total: 3.91s	remaining: 6.61s
372:	learn: 0.5178435	total: 3.92s	remaining: 6.6s
373:	learn: 0.5176890	total: 3.94s	remaining: 6.59s
374:	learn: 0.5175681	total: 3.95s	remaining: 6.58s
375:	learn: 0.5174505	total: 3.96s	remaining: 6.57s
376:	learn: 0.5173385	total: 3.97s	remaining: 6.56s
377:	learn: 0.5171942	total: 3.98s	remaining: 6.55s
378:	learn: 0.5170443	total: 3.99s	remaining: 6.53s
379:	learn: 0.5168974	total: 4s	remaining: 6.52s
380:	learn: 0.5167934	total: 4.01s	remaining: 6.51s
381:	learn: 0.5166411	total: 4.02s	remaining: 6.5s
382:	learn: 0.5165469	total: 4.03s	remaining: 6.49s
383:	learn: 0.5164616	total: 4.04s	remaining: 6.48s
384:	learn: 0.5163294	total: 4.05s	remaining: 6.47s
385:	learn: 0.5162106	total: 4.06s	remaining: 6.45s
386:	learn: 0.5160639	total: 4.07s	remaining: 6.44s

VotingClassifier(estimators=[('r1', RandomForestClassifier(n_estimators=500)),
                             ('r2', LGBMClassifier()),
                             ('r3', GradientBoostingClassifier()),
                             ('r4',
                              <catboost.core.CatBoostClassifier object at 0x7f3deef8dac0>)],
                 voting='soft')

In [26]:
model = soft_vote
pred_y = model.predict_proba(test)
pred_y = pred_y[:,1]

submission = pd.DataFrame({
    "index" : index,
    "voted" : pred_y
})
submission.to_csv('./data/model1.csv', index=False)

# **Model2: Lgbm Ensemble with different features**

## 1. Libraries

In [27]:
import pandas as pd
import numpy as np

from string import ascii_lowercase
from itertools import combinations

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_auc_score

In [28]:
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestRegressor
import eli5
from eli5.sklearn import PermutationImportance

import matplotlib.pyplot as plt

import warnings
import gc
warnings.filterwarnings("ignore")

## 2. Loading the data

In [29]:
train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test_x.csv')

## 3. Feature Engineering

In [30]:
x_train = train.copy()
x_train.drop('voted', axis=1, inplace = True)
y_train = train['voted']

In [31]:
dataset = [x_train, test]





### 마키아밸리 테스트 FE

In [32]:
questions = [i for i in list(ascii_lowercase)[:20]]
answers = [('Q'+i+'A') for i in questions]

In [33]:
for data in dataset:
  data['T'] = data['QcA'] - data['QfA'] + data['QoA'] - data['QrA'] + data['QsA']
  data['V'] = data['QbA'] - data['QeA'] + data['QhA'] + data['QjA'] + data['QmA'] - data['QqA']
  # data['M'] = - data['QkA']

In [34]:
flipping_columns = ["QeA", "QfA", "QkA", "QqA", "QrA"]
for data in dataset:
  for flip in flipping_columns: 
    data[flip] = 6 - data[flip]

In [35]:
flipping_secret_columns = ["QaA", "QdA", "QgA", "QiA", "QnA"]
for data in dataset:
  for flip in flipping_secret_columns: 
    data[flip] = 6 - data[flip]

In [36]:
for data in dataset:
  data['Mach_score'] = data[answers].mean(axis = 1)

In [37]:
for data in dataset:
  data['delay'] = data[[('Q'+i+'E') for i in questions]].sum(axis=1)
  data['delay'] = data['delay'] ** (1/10)
  data['delay_var'] = data['delay'].var()

In [38]:

Ancoms = list(combinations(answers, 2))
for data in dataset:
  for a,b in Ancoms:
    data['mach_%s_dv_%s'%(a,b)] = data[a]/data[b]

In [39]:
for data in dataset:
  data['mach_var'] = data[answers].var(axis=1)


### 나머지 Features

In [40]:
tps = ['tp01', 'tp02', 'tp03', 'tp04', 'tp05', 'tp06', 'tp07', 'tp08', 'tp09', 'tp10']
for data in dataset:
  for tp in tps:
    data[tp] = 7 - data[tp]

tipi feature들을 일반적인 형태로 복구시켜줬습니다.

In [41]:
for data in dataset:
  for tp in tps:
    data[tp] = data[tp].replace(0, np.nan)
    mean = data[tp].mean(axis=0)
    data[tp] = data[tp].replace(np.nan , mean)

tp중 무응답 값들을 평균값으로 대체했습니다.

In [42]:
for data in dataset:
  data['Ex'] = (data['tp01']+data['tp06'])/2
  data['Ag'] = (data['tp07']-data['tp02'])/2
  data['Con'] = (data['tp03']-data['tp08'])/2
  data['Es'] =(data['tp09']-data['tp04'])/2
  data['Op'] =(data['tp05']-data['tp10'])/2

In [43]:
index = test['index']
for data in dataset:
  data.drop('index', axis = 1, inplace = True)

In [44]:
import numpy as np
for data in dataset:
  teenager_ox = 1*np.array(data['age_group'] == '10s')
  data['teenager_ox'] = teenager_ox

10대인지 아닌지의 여부가 투표 여부에 큰 영향을 미칠 것 같아 하나의 column을 더 만들어주었습니다.

In [45]:
tpcoms = list(combinations(tps, 2))
for data in dataset:
  for a,b in tpcoms:
    data['tp_%s_dv_%s'%(a,b)] = data[a]/data[b]

tp 값들끼리 나눈 feature들을 생성해주었습니다.

In [46]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
needenco = ['age_group', 'gender', 'race', 'religion']
for i in needenco:
  x_train[i] = encoder.fit_transform(x_train[i])
  test[i] = encoder.transform(test[i])

In [47]:
for data in dataset:
  data['Es_gender'] = data['Es']*data['gender']
  data['Con_gender'] = data['Con']*data['gender']
  data['Op_gender'] = data['Op']*data['gender']

# SHAP

In [ ]:
from catboost import CatBoostClassifier
import shap
import matplotlib.pyplot as plt
plt.rc('font', family='Malgun Gothic')

X = x_train.copy()
y = list(map(lambda x: 0 if x==1 else 1, y_train))

model = CatBoostClassifier()
model.fit(X, y)

explainer = shap.TreeExplainer(model)
shap_values = explainer(X)
shap.initjs()

In [ ]:
import numpy as np

vals = np.abs(shap_values.values).mean(0)
feature_names = X.columns

feature_importance = pd.DataFrame(list(zip(feature_names, vals)),columns=['col_name','feature_importance_vals'])
feature_importance.sort_values(by=['feature_importance_vals'],ascending=False, inplace=True)
feature_importance.head()

In [ ]:
shap.plots.beeswarm(shap_values, max_display=350)

In [ ]:
# shap.plots.bar(shap_values, max_display=300)

In [ ]:
feature_importance[feature_importance['col_name']=='wr_08']

In [ ]:
temp_ls = []
for i in feature_importance.index:
    if i!=70:
        temp_ls.append(feature_importance.loc[i]['col_name'])
    else:
        break

In [ ]:
len(temp_ls)

EDA 결과, 성별에 따라 Emotional Stability/ Conscience/ Open Minded가 투표 여부에 미치는 영향이 크다고 판단되어 feature를 추가해주었습니다.

정보 출처: https://www.sciencedirect.com/science/article/abs/pii/S0261379413001613

## 4. Feature Selection 1 & Model 2-1

In [48]:
x_train = x_train
test = test

In [49]:
def lgbm_rfe_4040(x_data, y_data, ratio=0.9, min_feats=40):
    feats = x_data.columns.tolist()
    archive = pd.DataFrame(columns=['model', 'n_feats', 'feats', 'score'])
    while True:
        model = LGBMClassifier(objective = 'binary', num_iterations=10**4)
        x_train, x_val, y_train, y_val = train_test_split(x_data[feats], y_data, random_state=4040)
        model.fit(x_train, y_train, eval_set=[(x_val, y_val)], early_stopping_rounds=100, verbose=False)
        val_pred = model.predict_proba(x_val)
        val_pred = val_pred[:,1]
        score = roc_auc_score(y_val, val_pred)
        n_feats = len(feats)
        print(n_feats, score)
        archive = archive.append({'model': model, 'n_feats': n_feats, 'feats': feats, 'score': score}, ignore_index=True)
        feat_imp = pd.Series(model.feature_importances_, index=feats).sort_values(ascending=False)        
        next_n_feats = int(n_feats * ratio)
        if next_n_feats < min_feats:
            break
        else:
            feats = feat_imp.iloc[:next_n_feats].index.tolist()
    return archive

In [50]:
lgbm_archive_4040 = lgbm_rfe_4040(x_train, y_train)

326 0.7657604433861234
293 0.7657604433861234
263 0.7660072793456507
236 0.767402121602152
212 0.7663034016997157
190 0.7662282912232989
171 0.7669648213852982
153 0.7663662371913642
137 0.764458673482484
123 0.7650298021092214
110 0.7662878015924913
99 0.7658491651114727
89 0.7650935854161497
80 0.764219451121104
72 0.7654788645583153
64 0.7658633046508891
57 0.7674912628522975
51 0.7673306314693442
45 0.7654532580078116
40 0.7655709269440764

In [51]:
lgbm_archive_4040

,model,n_feats,feats,score
0,"LGBMClassifier(num_iterations=10000, objective...",326,"[QaA, QaE, QbA, QbE, QcA, QcE, QdA, QdE, QeA, ...",0.765760
1,"LGBMClassifier(num_iterations=10000, objective...",293,"[education, race, religion, teenager_ox, marri...",0.765760
2,"LGBMClassifier(num_iterations=10000, objective...",263,"[education, race, religion, teenager_ox, marri...",0.766007
3,"LGBMClassifier(num_iterations=10000, objective...",236,"[education, race, religion, teenager_ox, marri...",0.767402
4,"LGBMClassifier(num_iterations=10000, objective...",212,"[education, race, religion, married, teenager_...",0.766303
5,"LGBMClassifier(num_iterations=10000, objective...",190,"[education, race, religion, teenager_ox, marri...",0.766228
6,"LGBMClassifier(num_iterations=10000, objective...",171,"[education, race, religion, teenager_ox, marri...",0.766965
7,"LGBMClassifier(num_iterations=10000, objective...",153,"[education, race, religion, teenager_ox, marri...",0.766366
8,"LGBMClassifier(num_iterations=10000, objective...",137,"[education, race, religion, married, teenager_...",0.764459
9,"LGBMClassifier(num_iterations=10000, objective...",123,"[education, race, religion, QlE, QhE, QkE, tee...",0.765030
10,"LGBMClassifier(num_iterations=10000, objective...",110,"[education, race, religion, teenager_ox, marri...",0.766288
11,"LGBMClassifier(num_iterations=10000, objective...",99,"[education, race, religion, married, engnat, t...",0.765849
12,"LGBMClassifier(num_iterations=10000, objective...",89,"[education, race, religion, QeE, QoE, QsE, Mac...",0.765094
13,"LGBMClassifier(num_iterations=10000, objective...",80,"[education, race, religion, married, teenager_...",0.764219
14,"LGBMClassifier(num_iterations=10000, objective...",72,"[education, race, religion, married, age_group...",0.765479
15,"LGBMClassifier(num_iterations=10000, objective...",64,"[education, race, religion, married, teenager_...",0.765863
16,"LGBMClassifier(num_iterations=10000, objective...",57,"[education, race, QeE, religion, QcE, QoE, QlE...",0.767491
17,"LGBMClassifier(num_iterations=10000, objective...",51,"[education, race, religion, married, teenager_...",0.767331
18,"LGBMClassifier(num_iterations=10000, objective...",45,"[education, race, QeE, QdE, religion, QlE, QsE...",0.765453
19,"LGBMClassifier(num_iterations=10000, objective...",40,"[education, race, religion, QdE, married, QsE,...",0.765571

In [52]:
model = LGBMClassifier(objective="binary", num_iterations= 10**3)

x_train_1 = x_train[lgbm_archive_4040.iloc[16,2]]

model.fit(x_train_1, y_train)

pred_y1 = model.predict_proba(test[lgbm_archive_4040.iloc[16,2]])
pred_y1 = pred_y1[:,1]

## 5. Feature Selection 2 & Model 2-2

In [53]:
def lgbm_rfe_1234(x_data, y_data, ratio=0.9, min_feats=40):
    feats = x_data.columns.tolist()
    archive = pd.DataFrame(columns=['model', 'n_feats', 'feats', 'score'])
    while True:
        model = LGBMClassifier(objective = 'binary', num_iterations=10**4)
        x_train, x_val, y_train, y_val = train_test_split(x_data[feats], y_data, random_state=1234)
        model.fit(x_train, y_train, eval_set=[(x_val, y_val)], early_stopping_rounds=100, verbose=False)
        val_pred = model.predict_proba(x_val)
        val_pred = val_pred[:,1]
        score = roc_auc_score(y_val, val_pred)
        n_feats = len(feats)
        print(n_feats, score)
        archive = archive.append({'model': model, 'n_feats': n_feats, 'feats': feats, 'score': score}, ignore_index=True)
        feat_imp = pd.Series(model.feature_importances_, index=feats).sort_values(ascending=False)
        next_n_feats = int(n_feats * ratio)
        if next_n_feats < min_feats:
            break
        else:
            feats = feat_imp.iloc[:next_n_feats].index.tolist()
    return archive

In [54]:
lgbm_archive_1234 = lgbm_rfe_1234(x_train, y_train)

326 0.7602347615692592
293 0.7602347615692592
263 0.7615889599674073
236 0.7618358036388962
212 0.7616058418942144
190 0.760676619528091
171 0.760091483223663
153 0.7607334948017994
137 0.7613394220400719
123 0.7603031769792814
110 0.761862341280298
99 0.7621147136270788
89 0.7614385021307981
80 0.758855645197964
72 0.7607477447676929
64 0.7599520983113712
57 0.7593434300960527
51 0.7586410080067678
45 0.7598433469323171
40 0.7585046132512536

In [55]:
lgbm_archive_1234

,model,n_feats,feats,score
0,"LGBMClassifier(num_iterations=10000, objective...",326,"[QaA, QaE, QbA, QbE, QcA, QcE, QdA, QdE, QeA, ...",0.760235
1,"LGBMClassifier(num_iterations=10000, objective...",293,"[education, race, religion, teenager_ox, marri...",0.760235
2,"LGBMClassifier(num_iterations=10000, objective...",263,"[education, race, religion, teenager_ox, marri...",0.761589
3,"LGBMClassifier(num_iterations=10000, objective...",236,"[education, race, religion, teenager_ox, marri...",0.761836
4,"LGBMClassifier(num_iterations=10000, objective...",212,"[education, race, religion, teenager_ox, marri...",0.761606
5,"LGBMClassifier(num_iterations=10000, objective...",190,"[education, race, religion, teenager_ox, marri...",0.760677
6,"LGBMClassifier(num_iterations=10000, objective...",171,"[education, race, religion, teenager_ox, marri...",0.760091
7,"LGBMClassifier(num_iterations=10000, objective...",153,"[education, race, religion, teenager_ox, marri...",0.760733
8,"LGBMClassifier(num_iterations=10000, objective...",137,"[education, race, religion, teenager_ox, marri...",0.761339
9,"LGBMClassifier(num_iterations=10000, objective...",123,"[education, race, religion, teenager_ox, marri...",0.760303
10,"LGBMClassifier(num_iterations=10000, objective...",110,"[education, race, religion, age_group, teenage...",0.761862
11,"LGBMClassifier(num_iterations=10000, objective...",99,"[education, race, religion, teenager_ox, age_g...",0.762115
12,"LGBMClassifier(num_iterations=10000, objective...",89,"[education, race, religion, age_group, teenage...",0.761439
13,"LGBMClassifier(num_iterations=10000, objective...",80,"[education, race, religion, age_group, teenage...",0.758856
14,"LGBMClassifier(num_iterations=10000, objective...",72,"[education, race, religion, married, teenager_...",0.760748
15,"LGBMClassifier(num_iterations=10000, objective...",64,"[education, race, religion, teenager_ox, marri...",0.759952
16,"LGBMClassifier(num_iterations=10000, objective...",57,"[education, race, religion, teenager_ox, marri...",0.759343
17,"LGBMClassifier(num_iterations=10000, objective...",51,"[education, race, religion, married, age_group...",0.758641
18,"LGBMClassifier(num_iterations=10000, objective...",45,"[education, race, religion, married, age_group...",0.759843
19,"LGBMClassifier(num_iterations=10000, objective...",40,"[education, race, religion, tp_tp06_dv_tp09, a...",0.758505

In [56]:
model2 = LGBMClassifier(objective="binary", num_iterations= 10**3)

x_train_2 = x_train[lgbm_archive_1234.iloc[11,2]]

model2.fit(x_train_2, y_train)

pred_y2 = model2.predict_proba(test[lgbm_archive_1234.iloc[11,2]])
pred_y2 = pred_y2[:,1]

## 6. Feature Selection 3 & Model 2-3

In [57]:
def lgbm_rfe_99087(x_data, y_data, ratio=0.9, min_feats=40):
    feats = x_data.columns.tolist()
    archive = pd.DataFrame(columns=['model', 'n_feats', 'feats', 'score'])
    while True:
        model = LGBMClassifier(objective = 'binary', num_iterations=10**4)
        x_train, x_val, y_train, y_val = train_test_split(x_data[feats], y_data, random_state=99087)
        model.fit(x_train, y_train, eval_set=[(x_val, y_val)], early_stopping_rounds=100, verbose=False)
        val_pred = model.predict_proba(x_val)
        val_pred = val_pred[:,1]
        score = roc_auc_score(y_val, val_pred)
        n_feats = len(feats)
        print(n_feats, score)
        archive = archive.append({'model': model, 'n_feats': n_feats, 'feats': feats, 'score': score}, ignore_index=True)
        feat_imp = pd.Series(model.feature_importances_, index=feats).sort_values(ascending=False)
        next_n_feats = int(n_feats * ratio)
        if next_n_feats < min_feats:
            break
        else:
            feats = feat_imp.iloc[:next_n_feats].index.tolist()
    return archive

In [58]:
lgbm_archive_99087 = lgbm_rfe_99087(x_train, y_train)

326 0.7603119723843995
293 0.7605067064732967
263 0.7609278339218781
236 0.7599520310682977
212 0.7604709847297095
190 0.7603586207789662
171 0.7598230592306667
153 0.7582222581670646
137 0.7591100252116129
123 0.7598585163687459
110 0.7595193854976009
99 0.7589942836493844
89 0.7595497995659971
80 0.7601810237879729
72 0.7598538779898399
64 0.7601956393510353
57 0.7587437489283477
51 0.7581888867429902
45 0.7589496742737326
40 0.7578052554514025

In [59]:
lgbm_archive_99087

,model,n_feats,feats,score
0,"LGBMClassifier(num_iterations=10000, objective...",326,"[QaA, QaE, QbA, QbE, QcA, QcE, QdA, QdE, QeA, ...",0.760312
1,"LGBMClassifier(num_iterations=10000, objective...",293,"[education, race, teenager_ox, religion, marri...",0.760507
2,"LGBMClassifier(num_iterations=10000, objective...",263,"[education, race, teenager_ox, religion, marri...",0.760928
3,"LGBMClassifier(num_iterations=10000, objective...",236,"[education, race, religion, teenager_ox, age_g...",0.759952
4,"LGBMClassifier(num_iterations=10000, objective...",212,"[education, race, religion, teenager_ox, marri...",0.760471
5,"LGBMClassifier(num_iterations=10000, objective...",190,"[education, race, teenager_ox, religion, marri...",0.760359
6,"LGBMClassifier(num_iterations=10000, objective...",171,"[education, race, religion, teenager_ox, age_g...",0.759823
7,"LGBMClassifier(num_iterations=10000, objective...",153,"[education, race, religion, teenager_ox, marri...",0.758222
8,"LGBMClassifier(num_iterations=10000, objective...",137,"[education, race, religion, teenager_ox, age_g...",0.759110
9,"LGBMClassifier(num_iterations=10000, objective...",123,"[education, race, religion, teenager_ox, marri...",0.759859
10,"LGBMClassifier(num_iterations=10000, objective...",110,"[education, race, religion, teenager_ox, age_g...",0.759519
11,"LGBMClassifier(num_iterations=10000, objective...",99,"[education, race, religion, teenager_ox, QsE, ...",0.758994
12,"LGBMClassifier(num_iterations=10000, objective...",89,"[education, race, religion, teenager_ox, age_g...",0.759550
13,"LGBMClassifier(num_iterations=10000, objective...",80,"[education, race, religion, teenager_ox, age_g...",0.760181
14,"LGBMClassifier(num_iterations=10000, objective...",72,"[education, race, religion, teenager_ox, age_g...",0.759854
15,"LGBMClassifier(num_iterations=10000, objective...",64,"[education, race, religion, teenager_ox, tp_tp...",0.760196
16,"LGBMClassifier(num_iterations=10000, objective...",57,"[education, race, religion, teenager_ox, mach_...",0.758744
17,"LGBMClassifier(num_iterations=10000, objective...",51,"[education, race, religion, teenager_ox, age_g...",0.758189
18,"LGBMClassifier(num_iterations=10000, objective...",45,"[education, race, religion, teenager_ox, marri...",0.758950
19,"LGBMClassifier(num_iterations=10000, objective...",40,"[education, race, religion, QlE, teenager_ox, ...",0.757805

In [60]:
model3 = LGBMClassifier(objective="binary", num_iterations= 10**3)

x_train_3 = x_train[lgbm_archive_99087.iloc[2,2]]

model3.fit(x_train_3, y_train)

pred_y3 = model3.predict_proba(test[lgbm_archive_99087.iloc[2,2]])
pred_y3 = pred_y3[:,1]

## 7. Feature Selection 4 & Model 2-4

In [61]:
def lgbm_rfe_42(x_data, y_data, ratio=0.9, min_feats=40):
    feats = x_data.columns.tolist()
    archive = pd.DataFrame(columns=['model', 'n_feats', 'feats', 'score'])
    while True:
        model = LGBMClassifier(objective = 'binary', num_iterations=10**4)
        x_train, x_val, y_train, y_val = train_test_split(x_data[feats], y_data, random_state=42)
        model.fit(x_train, y_train, eval_set=[(x_val, y_val)], early_stopping_rounds=100, verbose=False)
        val_pred = model.predict_proba(x_val)
        val_pred = val_pred[:,1]
        score = roc_auc_score(y_val, val_pred)
        n_feats = len(feats)
        print(n_feats, score)
        archive = archive.append({'model': model, 'n_feats': n_feats, 'feats': feats, 'score': score}, ignore_index=True)
        feat_imp = pd.Series(model.feature_importances_, index=feats).sort_values(ascending=False)
        next_n_feats = int(n_feats * ratio)
        if next_n_feats < min_feats:
            break
        else:
            feats = feat_imp.iloc[:next_n_feats].index.tolist()
    return archive

In [62]:
lgbm_archive_42 = lgbm_rfe_42(x_train, y_train)

326 0.768031830395951
293 0.768031830395951
263 0.768487993930189
236 0.7691866373503328
212 0.7698177263536815
190 0.7680693744635338
171 0.768743004070823
153 0.7683404638006077
137 0.7680315813474099
123 0.7694577266874066
110 0.7673551966406341
99 0.7668502507233925
89 0.7671422134413242
80 0.7676553312638229
72 0.7669653734115528
64 0.7682408755152037
57 0.7696710056318592
51 0.7704799152936102
45 0.770109953685688
40 0.7698090407858079

In [63]:
lgbm_archive_42

,model,n_feats,feats,score
0,"LGBMClassifier(num_iterations=10000, objective...",326,"[QaA, QaE, QbA, QbE, QcA, QcE, QdA, QdE, QeA, ...",0.768032
1,"LGBMClassifier(num_iterations=10000, objective...",293,"[education, race, religion, teenager_ox, age_g...",0.768032
2,"LGBMClassifier(num_iterations=10000, objective...",263,"[education, race, religion, teenager_ox, age_g...",0.768488
3,"LGBMClassifier(num_iterations=10000, objective...",236,"[education, race, religion, teenager_ox, age_g...",0.769187
4,"LGBMClassifier(num_iterations=10000, objective...",212,"[education, race, religion, teenager_ox, age_g...",0.769818
5,"LGBMClassifier(num_iterations=10000, objective...",190,"[education, race, religion, teenager_ox, QkE, ...",0.768069
6,"LGBMClassifier(num_iterations=10000, objective...",171,"[education, race, religion, teenager_ox, age_g...",0.768743
7,"LGBMClassifier(num_iterations=10000, objective...",153,"[education, race, religion, teenager_ox, marri...",0.768340
8,"LGBMClassifier(num_iterations=10000, objective...",137,"[education, race, religion, teenager_ox, QfE, ...",0.768032
9,"LGBMClassifier(num_iterations=10000, objective...",123,"[education, race, religion, teenager_ox, age_g...",0.769458
10,"LGBMClassifier(num_iterations=10000, objective...",110,"[education, race, religion, mach_var, QpE, tee...",0.767355
11,"LGBMClassifier(num_iterations=10000, objective...",99,"[education, race, religion, QhE, teenager_ox, ...",0.766850
12,"LGBMClassifier(num_iterations=10000, objective...",89,"[education, race, religion, teenager_ox, QeE, ...",0.767142
13,"LGBMClassifier(num_iterations=10000, objective...",80,"[education, race, religion, teenager_ox, age_g...",0.767655
14,"LGBMClassifier(num_iterations=10000, objective...",72,"[education, race, religion, tp_tp03_dv_tp06, t...",0.766965
15,"LGBMClassifier(num_iterations=10000, objective...",64,"[education, race, religion, QkE, QeE, tp_tp03_...",0.768241
16,"LGBMClassifier(num_iterations=10000, objective...",57,"[education, race, religion, QeE, QsE, QkE, mac...",0.769671
17,"LGBMClassifier(num_iterations=10000, objective...",51,"[education, race, religion, tp_tp03_dv_tp06, Q...",0.770480
18,"LGBMClassifier(num_iterations=10000, objective...",45,"[education, religion, QqE, QsE, race, QkE, QiE...",0.770110
19,"LGBMClassifier(num_iterations=10000, objective...",40,"[education, race, religion, QkE, QcE, QiE, tp_...",0.769809

In [64]:
model4 = LGBMClassifier(objective="binary", num_iterations= 10**3)

x_train_4 = x_train[lgbm_archive_42.iloc[17,2]]

model4.fit(x_train_4, y_train)

pred_y4 = model4.predict_proba(test[lgbm_archive_42.iloc[17,2]])
pred_y4 = pred_y4[:,1]

## 8. Ensemble

In [65]:
pred_all = (pred_y + pred_y2 + pred_y3 + pred_y4) * (1/4)

submission = pd.DataFrame({
    "index" : index,
    "voted" : pred_all
})
submission.to_csv('./data/model2.csv', index=False)

# **Model3: NN**

3번째 모델은 Junho Sun 님께서 공유해주신 코드를 그대로 활용하였습니다.

좋은 모델을 공유해주신 덕분에 public score도 0.78대로 올라갈 수 있었습니다. 
정말 감사합니다!

In [ ]:
import random
from datetime import datetime

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import StratifiedKFold
from torch import nn, optim
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset
from tqdm import tqdm

random.seed(0)
np.random.seed(0)
torch.manual_seed(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

DEVICE = 'cuda:0' if torch.cuda.is_available() else 'cpu'

drop_list = ['QaE', 'QbE', 'QcE', 'QdE', 'QeE',
             'QfE', 'QgE', 'QhE', 'QiE', 'QjE',
             'QkE', 'QlE', 'QmE', 'QnE', 'QoE',
             'QpE', 'QqE', 'QrE', 'QsE', 'QtE',
             'index', 'hand']
replace_dict = {'education': str, 'engnat': str, 'married': str, 'urban': str}
train_data = pd.read_csv('./data/train.csv')
test_data = pd.read_csv('./data/test_x.csv')
train_data = train_data.drop(train_data[train_data.familysize > 50].index)
train_y = train_data['voted']
train_x = train_data.drop(drop_list + ['voted'], axis=1)
test_x = test_data.drop(drop_list, axis=1)
train_x = train_x.astype(replace_dict)
test_x = test_x.astype(replace_dict)
train_x = pd.get_dummies(train_x)
test_x = pd.get_dummies(test_x)
train_y = 2 - train_y.to_numpy()
train_x = train_x.to_numpy()
test_x = test_x.to_numpy()

train_y_t = torch.tensor(train_y, dtype=torch.float32)
train_x_t = torch.tensor(train_x, dtype=torch.float32)
test_x_t = torch.tensor(test_x, dtype=torch.float32)
train_x_t[:, :20] = (train_x_t[:, :20] - 3.) / 2.
test_x_t[:, :20] = (test_x_t[:, :20] - 3.) / 2
train_x_t[:, 20] = (train_x_t[:, 20] - 5.) / 4.
test_x_t[:, 20] = (test_x_t[:, 20] - 5.) / 4.
train_x_t[:, 21:31] = (train_x_t[:, 21:31] - 3.5) / 3.5
test_x_t[:, 21:31] = (test_x_t[:, 21:31] - 3.5) / 3.5
test_len = len(test_x_t)

N_REPEAT = 5
N_SKFOLD = 7
N_EPOCH = 48
BATCH_SIZE = 7200
LOADER_PARAM = {
    'batch_size': BATCH_SIZE,
    'num_workers': 4,
    'pin_memory': True
}
prediction = np.zeros((test_len, 1), dtype=np.float32)

for repeat in range(N_REPEAT):

    skf, tot = StratifiedKFold(n_splits=N_SKFOLD, random_state=repeat, shuffle=True), 0.
    for skfold, (train_idx, valid_idx) in enumerate(skf.split(train_x, train_y)):
        train_idx, valid_idx = list(train_idx), list(valid_idx)
        train_loader = DataLoader(TensorDataset(train_x_t[train_idx, :], train_y_t[train_idx]),
                                  shuffle=True, drop_last=True, **LOADER_PARAM)
        valid_loader = DataLoader(TensorDataset(train_x_t[valid_idx, :], train_y_t[valid_idx]),
                                  shuffle=False, drop_last=False, **LOADER_PARAM)
        test_loader = DataLoader(TensorDataset(test_x_t, torch.zeros((test_len,), dtype=torch.float32)),
                                 shuffle=False, drop_last=False, **LOADER_PARAM)
        model = nn.Sequential(
            nn.Dropout(0.05),
            nn.Linear(91, 180, bias=False),
            nn.LeakyReLU(0.05, inplace=True),
            nn.Dropout(0.5),
            nn.Linear(180, 32, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(32, 1)
        ).to(DEVICE)
        criterion = torch.nn.BCEWithLogitsLoss(pos_weight=torch.tensor([1.20665], device=DEVICE))
        optimizer = optim.AdamW(model.parameters(), lr=5e-3, weight_decay=7.8e-2)
        scheduler = optim.lr_scheduler.CosineAnnealingWarmRestarts(
            optimizer, T_0=N_EPOCH // 6, eta_min=4e-4)
        prediction_t, loss_t = np.zeros((test_len, 1), dtype=np.float32), 1.

        # for epoch in range(N_EPOCH):
        for epoch in tqdm(range(N_EPOCH), desc='{:02d}/{:02d}'.format(skfold + 1, N_SKFOLD)):
            model.train()
            for idx, (xx, yy) in enumerate(train_loader):
                optimizer.zero_grad()
                xx, yy = xx.to(DEVICE), yy.to(DEVICE)
                pred = model(xx).squeeze()
                loss = criterion(pred, yy)
                loss.backward()
                optimizer.step()
                scheduler.step(epoch + idx / len(train_loader))

            with torch.no_grad():
                model.eval()
                running_acc, running_loss, running_count = 0, 0., 0
                for xx, yy in valid_loader:
                    xx, yy = xx.to(DEVICE), yy.to(DEVICE)
                    pred = model(xx).squeeze()
                    loss = criterion(pred, yy)
                    running_loss += loss.item() * len(yy)
                    running_count += len(yy)
                    running_acc += ((torch.sigmoid(pred) > 0.5).float() == yy).sum().item()
                # print('R{:02d} S{:02d} E{:02d} | {:6.4f}, {:5.2f}%'
                #       .format(repeat + 1, skfold + 1, epoch + 1, running_loss / running_count,
                #               running_acc / running_count * 100))

                if running_loss / running_count < loss_t:
                    loss_t = running_loss / running_count
                    for idx, (xx, _) in enumerate(test_loader):
                        xx = xx.to(DEVICE)
                        pred = (2. - torch.sigmoid(model(xx).detach().to('cpu'))).numpy()
                        prediction_t[BATCH_SIZE * idx:min(BATCH_SIZE * (idx + 1), len(prediction)), :] \
                            = pred[:, :].copy()
        prediction[:, :] += prediction_t[:, :].copy() / (N_REPEAT * N_SKFOLD)
        tot += loss_t
    print('R{} -> {:6.4f}'.format(repeat + 1, tot / N_SKFOLD))

df = pd.read_csv('./data/sample_submission.csv')
df.iloc[:, 1:] = prediction

In [ ]:
df.to_csv('./data/model3.csv', index=False)

# Final Ensemble

In [101]:
model1 = pd.read_csv('./data/model1.csv', index_col = 'index')
model2 = pd.read_csv('./data/model2.csv', index_col='index')

pred_y = (model1)*(0.7) + (model2)*(0.3)

test = pd.read_csv('./data/test_x.csv')
index = test['index']

submission = pd.DataFrame({
    'index': index,
    'voted': pred_y['voted']
    })

submission.to_csv('./data/combined_model1_model2.csv', index=False)

In [67]:

combined_12 = pd.read_csv('./data/combined_model1_model2.csv', index_col = 'index')
model3 = pd.read_csv('./data/model3.csv', index_col='index')
model3['voted'] = model3['voted']-1

다른 모델과 같이 [0,1]의 범위(voted가 2일 확률)를 맞춰주기 위해 1을 빼주었습니다.

In [68]:
pred_y = (model3)*(0.8) + (model1)*(0.2)

test = pd.read_csv('./data/test_x.csv')
index = test['index']

submission = pd.DataFrame({
    'index': index,
    'voted': pred_y['voted']
    })

submission.to_csv('./data/submission_final_FE.csv', index=False)